# Site settings
title: Design Portfolio
email: info@website-design.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web deisgner and developer, specializing in Jekyll, Html, CSS and Javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: isentchenko
github_username:  ityulkanov
google_username: ityulkanov

permalink: /:categories/:title
links: 
 -title: about
 url: /about
 -title: work
 url: /work
 -title: articles
 url: /articles
 -title: hire me
 url: /hire-me

# Build settings
markdown: kramdown
